### ISSUE TITLE
[Beta] Movement stops suddenly even if key is still pressed down

### ISSUE THREAD

**Issue by Jabelius** [IronWillGames/Dransik#303] opened 2022-11-26 06:44 UTC
I just tested beta and test builds and movement stops suddenly. I can still move to same direction but I need to press the same direction button again. Ping issue? Must have been something with new movement as this problem was not occuring at production build.

**Comment by davidjreese** [comment] 2022-11-27 18:50
Closing this as not reproducible. maybe a bad build or something

**Closed as completed by davidjreese** 2022-11-27 18:50 UTC
Labels: bug, wontfix, Dransik2.0

**Comment by Jabelius** [comment] 2022-11-28 13:40
Btw. My weight is 592 / 522 so could that be the reason?
Edit - After a short test: No. Even if I dropped to 520 / 522 I still get "invisible temp walls" movement bug.

**Comment by davidjreese** [comment] 2022-11-28 13:49
Yeah, we have an issue to better notify player when they can't move or pickup anything due to encumbered. It is something will will fix post launching the new client. It  requires some server/data work
