### ISSUE TITLE
[Dransik 2.0] Attempting to use Lumberjack axe, causes merchants and banks to be not functional

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#170] opened 2022-10-13 02:50 UTC
### Attempting to use Lumberjack axe, causes merchants and banks to be not functional

1. Log into a character
2. Purchase a lumberjack axe from the Key store
3. Click on the lumberjack axe
4. Notice the Chat Console says "Where would you like to chop?". Also notice that a bubble appears above your character avatar briefly then vanishes.
5. Go to any merchant and try to click them to open their shop
6. Notice that the merchants to do not work
7. Go to any bank and try to click them to open the bank
8. Notice that the banks do not work

NOTE: The game requires a relog to get things to work properly again.

#### Expected:
After clicking a lumberjack axe, should be able to cut trees to get wood.

#### Actual:
After clicking a lumberjack axe, all merchants and banks become not functional.

**Comment by davidjreese** [comment] 2022-10-16 18:59
cannot reproduce - this may have been fixed with some of the other work. let me know.

**Closed as completed by davidjreese** 2022-10-16 18:59 UTC
Labels: Dransik2.0
