### ISSUE TITLE
Targeting when creature on edge of screen or off screen drops target

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#30] opened 2022-09-08 14:23 UTC
From codecks: Target sometimes is bugged ( when target being on the edges of the screen or leaving ur screen for second) and u wont swing or it and u need to retarget.

**Comment by AESeryth** [comment] 2022-10-31 00:57
Seems to be fixed by the new client but I don't have a 100% reproduction for this one.

**Comment by davidjreese** [comment] 2022-12-03 01:09
flagging this as fixed. if it shows up again, will look

**Closed as completed by davidjreese** 2022-12-03 01:09 UTC
Labels: bug, help wanted
