### ISSUE TITLE
Dark Blade not dropping, not craftable.

### ISSUE THREAD

**Issue by Fluffp** [IronWillGames/Dransik#676] opened 2023-05-13 12:48 UTC
"The Dark Blade is a craftable item from Dark Ore.. you combine the Dark Blade and Dark Hilt to make the Dark Sword"

this was posted by the tyrant in discord but there is no blade to craft, also based on that TC7 list it's not on there.

**Comment by hgesler** [comment] 2023-08-17 13:13
I'm not sure what the design is here for this. The Hilt is craftable but not the Blade.

**Comment by davidjreese** [comment] 2024-02-23 14:36
@hgesler - i think this is working properly now. May want to check with Pat or others?

**Comment by Galdelonian** [comment] 2024-03-05 05:24
This is working properly. The blade drops from Drasbixz or however you spell it the boss from the Tower. You hunt for blade and craft hilt then mix them together at the Tower in a special spot. If you'd like I can show you in-game so you can see how it works. It doesn't seem to require a skill to do so. It's a special event.

**Comment by davidjreese** [comment] 2024-04-22 01:49
closing this as not a bug

**Closed as completed by davidjreese** 2024-04-22 01:49 UTC
Labels: invalid
